"Resource/UI/HudDemomanPipes.res"
{
	"background"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"background"
		"xpos"				"999999"
	}
	"ChargeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"ChargeLabel"
		"xpos"				"999999"
	}
	"PlayerStickyBG"
	{
		"ControlName"					"CExImageButton"
		"fieldName"						"PlayerStickyBG"
		"xpos"							"99999"
		"ypos"							"99999"
		"zpos"							"0"
		"wide"							"0"
		"tall"							"0"
		"visible"						"0"
		"enabled"						"1"
		"defaultbgcolor_override"		"0 0 0 0"
		"PaintBackgroundType"			"0"
		"TextInsetX"					"0"
	}
	"ChargeMeter"
	{
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ChargeMeter"
		"font"					"Default"
		"xpos"					"c-25"
		"ypos"					"c160"
		"zpos"					"2"
		"wide"					"50"
		"tall"					"4"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"textAlignment"			"Left"
		"dulltext"				"0"
		"brighttext"			"0"
		"MeterFG"				"255 255 255 255"
		"MeterFG_override"		"255 255 255 255"
		"fgcolor"				"255 255 255 255"
		"fgcolor_override"		"255 255 255 255"
		"MeterBG"				"0 0 0 130"
		"MeterBG_override"		"0 0 0 130"
		"bgcolor"				"0 0 0 130"
		"bgcolor_override"		"0 0 0 130"
	}
	"PipesPresentPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"PipesPresentPanel"
		"xpos"				"cs-0.5+37"
		"ypos"				"c112-1"
		"zpos"				"1"
		"wide"				"20"
		"tall"				"20"
		"visible"			"1"
		"PipeIcon"
		{
			"ControlName"		"CTFImagePanel"
			"fieldName"			"PipeIcon"
			"xpos"				"999999"
		}
		"NumPipesLabel"
		{
			"ControlName"				"CExLabel"
			"fieldName"					"NumPipesLabel"
			"xpos"						"0"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"f0"
			"tall"						"f0"
			"autoResize"				"1"
			"pinCorner"					"2"
			"visible"					"1"
			"enabled"					"1"
			"tabPosition"				"0"
			"labelText"					"%activepipes%"
			"textAlignment"				"center"
			"font"						"volkswagen16"
			"fgcolor"					"255 255 255 255"
			"proportionaltoparent"		"1"
		}
		"NumPipesLabelDropshadow"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"NumPipesLabelDropshadow"
			"xpos"				"999999"
		}
		"PlayerStickyBG1"
		{
			"ControlName"				"EditablePanel"
			"fieldName"					"PlayerStickyBG1"
			"xpos"						"0"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"f0"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"TextInsetX"				"9999"
			"PaintBackground"			"1"
			"PaintBackgroundType"		"2"
			"bgcolor_override"			"0 0 0 130"
			"proportionaltoparent"		"1"
			"stars"
			{
				"ControlName"				"CTFParticlePanel"
				"fieldName"					"stars"
				"xpos"						"0"
				"ypos"						"0"
				"zpos"						"100"
				"wide"						"f0"
				"tall"						"f0"
				"visible"					"1"
				"proportionaltoparent"		"1"
				"ParticleEffects"
				{
					"0"
					{
						"particle_xpos"			"cs-0.5"
						"particle_ypos"			"15"
						"particle_scale"		"3"
						"particleName"			"_stars"
						"start_activated"		"1"
						"loop"					"1"
						"angles"				"0 0 0"
					}
				}
			}
		}
	}
	"NoPipesPresentPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"NoPipesPresentPanel"
		"xpos"				"c30"
		"ypos"				"c115"
		"zpos"				"1"
		"wide"				"20"
		"tall"				"20"
		"visible"			"1"
		"PipeIcon"
		{
			"ControlName"		"CTFImagePanel"
			"fieldName"			"PipeIcon"
			"xpos"				"999999"
		}
		"NumPipesLabel"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"NumPipesLabel"
			"xpos"				"0"
			"ypos"				"0"
			"zpos"				"0"
			"wide"				"20"
			"tall"				"20"
			"autoResize"		"1"
			"pinCorner"			"2"
			"visible"			"0"
			"enabled"			"1"
			"tabPosition"		"0"
			"labelText"			"%activepipes%"
			"textAlignment"		"center"
			"font"				"roboto18"
			"fgcolor"			"255 255 255 255"
		}
		"NumPipesLabelDropshadow"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"NumPipesLabelDropshadow"
			"xpos"				"999999"
		}
	}
}