#base "base/classloadoutpanel.res"

"resource/ui/classloadoutpanel.res"
{
	"bgcolor_override"	"46 43 42 0" 
	"infocus_bgcolor_override" "46 43 42 0" 
	"outoffocus_bgcolor_override" "46 43 42 0"
	"PresetsExplanation"	{	"xpos"	"9999"	"visible"	"0"	"enabled"	"0"	}
	"TauntsExplanation"		{	"xpos"	"9999"	"visible"	"0"	"enabled"	"0"	}
	"ToggleToRED"
	{
		"ControlName"								"CExImageButton"
		"fieldName"									"ToggleToRED"
		"xpos"										"c122"
		"ypos"										"c-47"
		"zpos"										"12"
		"wide"										"25"
		"tall"										"12"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"#TF_ScoreBoard_Red"
		"textAlignment"								"center"
		"scaleImage"								"1"
		"Command"									"sv_cheats 1; r_skin 0"
		"paintborder"								"0"
		"paintbackground"							"1"
		"paintbackgroundtype"						"2"
		"fgcolor"									"TanLight"
		"defaultFgColor_override" 					"TanLight"
		"armedFgColor_override" 					"TanLight"
		"depressedFgColor_override"					"TanLight"
		"selectedFgColor_override" 					"TanLight"
		
		"bgcolor"									"HUDRedTeamSolid"
		"defaultBgColor_override" 					"HUDRedTeamSolid"
		"armedBgColor_override" 					"HUDRedTeamSolid"
		"depressedBgColor_override" 				"HUDRedTeamSolid"
		"selectedBgColor_override" 					"HUDRedTeamSolid"
	}
	
	"ToggleToBLU"
	{
		"ControlName"								"CExImageButton"
		"fieldName"									"ToggleToBLU"
		"xpos"										"c122"
		"ypos"										"c-32"
		"zpos"										"12"
		"wide"										"25"
		"tall"										"12"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"#TF_ScoreBoard_Blue"
		"textAlignment"								"center"
		"scaleImage"								"1"
		"Command"									"sv_cheats 1; r_skin 1"
		"paintborder"								"0"
		"paintbackground"							"1"
		"paintbackgroundtype"						"2"
		"fgcolor"									"TanLight"
		"defaultFgColor_override" 					"TanLight"
		"armedFgColor_override" 					"TanLight"
		"depressedFgColor_override" 				"TanLight"
		"selectedFgColor_override" 					"TanLight"
		
		"bgcolor_override"							"HUDBlueTeamSolid"
		"defaultBgColor_override" 					"HUDBlueTeamSolid"
		"armedBgColor_override" 					"HUDBlueTeamSolid"
		"depressedBgColor_override" 				"HUDBlueTeamSolid"
		"selectedBgColor_override" 					"HUDBlueTeamSolid"
	}
	
	"CharacterLoadoutButton"
	{
		"ControlName"								"CExButton"
		"fieldName"									"CharacterLoadoutButton"
		"xpos"										"c-25"
		"ypos"										"c90"
		"zpos"										"2"
		"wide"										"25"
		"tall"										"25"
		"visible"									"1"
		"enabled"									"1"
		"textAlignment"								"center"
		"labeltext"									"P"
		"font"										"m0reSymbols"
		"Command"									"characterloadout"
		"sound_depressed"							"UI/buttonclick.wav"
		"sound_released"							"UI/buttonclickrelease.wav"

		"defaultFgColor_override" 					"TanLight"
		"armedFgColor_override" 					"TanLight"
		"depressedFgColor_override" 				"TanLight"
	}

	"TauntLoadoutButton"
	{
		"ControlName"								"CExButton"
		"fieldName"									"TauntLoadoutButton"
		"xpos"										"c2"
		"ypos"										"c90"
		"zpos"										"2"
		"wide"										"25"
		"tall"										"25"
		"visible"									"1"
		"enabled"									"1"
		"textAlignment"								"center"
		"labeltext"									"Q"
		"font"										"m0reSymbols"
		"Command"									"tauntloadout"
		"sound_depressed"							"UI/buttonclick.wav"
		"sound_released"							"UI/buttonclickrelease.wav"

		"defaultFgColor_override" 					"TanLight"
		"armedFgColor_override" 					"TanLight"
		"depressedFgColor_override" 				"TanLight"
	}	
	"custombg"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"custombg"
		"xpos"										"0"
		"ypos"										"-24"
		"zpos"										"-5"
		"wide"										"f0"
		"tall"										"f0"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage" 								"1"
		"image"										"../console/bgblur"
	}
	TopLine{ "xpos" "c-9305" "visible" "0" }
}
