"resource/optionssubdifficulty.res"
{
	"OptionsSubMultiplayer"
	{
		"ControlName"		"COptionsSubMultiplayer"
		"fieldName"		"OptionsSubMultiplayer"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"496"
		"tall"		"305"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"810"
		"ypos"		"603"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"Command"		"Close"
		"Default"		"0"
		"selected"		"0"
	}
	"ok"
	{
		"ControlName"		"Button"
		"fieldName"		"OK"
		"xpos"		"740"
		"ypos"		"603"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_OK"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"Command"		"Ok"
		"Default"		"0"
		"selected"		"0"
	}
	"Apply"
	{
		"ControlName"		"Button"
		"fieldName"		"Apply"
		"xpos"		"880"
		"ypos"		"603"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Apply"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"Command"		"Apply"
		"Default"		"0"
		"selected"		"0"
	}
	"LogoImage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"LogoImage"
		"xpos"		"32"
		"ypos"		"38"
		"wide"		"256"
		"tall"		"256"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"replay/thumbnails/menu/hos"
		"border"		"DepressedBorder"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}
	"Label11"
	{
		"ControlName"		"Label"
		"fieldName"		"Label11"
		"xpos"		"32"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"The hud should work if you see this."
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
	}

	
	"Skill1Radio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"Skill1Radio"
		"xpos"		"34"
		"ypos"		"58"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		"#GameUI_SkillEasy"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
		"SubTabPosition"		"1"
	}
	"Skill2Radio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"Skill2Radio"
		"xpos"		"34"
		"ypos"		"116"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		"#GameUI_SkillNormal"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
		"SubTabPosition"		"2"
	}
	"Skill3Radio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"Skill3Radio"
		"xpos"		"34"
		"ypos"		"176"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		"#GameUI_SkillHard"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
		"SubTabPosition"		"3"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"36"
		"ypos"		"24"
		"wide"		"212"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_SelectDifficulty"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"60"
		"ypos"		"80"
		"wide"		"0"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_EasyDescription"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"1"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"60"
		"ypos"		"138"
		"wide"		"0"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_NormalDescription"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"1"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"fieldName"		"Label4"
		"xpos"		"60"
		"ypos"		"198"
		"wide"		"0"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HardDescription"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"1"
	}
}
