"Resource/UI/ItemModelPanel.res"
{
	"itemmodelpanel"
	{
		"ControlName"	"CEmbeddedItemModelPanel"
		"fieldName"		"itemmodelpanel"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
	}
	"anchordisguise"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"anchordisguise"
		"xpos"			"c6"		
		"ypos"			"c122"  
		"ypos_minmode"			"c144"   	
		"zpos"			"2"
		"wide"			"1"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"	
	}
	"DisguiseNameLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"DisguiseNameLabel"
		"font"			"m0refont9"
		"xpos"			"1"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"180"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor"		"white"
		"labelText"		"%disguisename%"
		"textAlignment"	"center"
		"auto_wide_tocontents" "1"
		"pin_to_sibling" "anchordisguise"
   		"pin_corner_to_sibling"  "PIN_CENTER_TOP"
    	"pin_to_sibling_corner"  "PIN_CENTER_TOP"
	}
	"DisguiseNameLabelShadow"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"DisguiseNameLabelShadow"
		"font"			"m0refont9"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"180"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor"		"black"
		"labelText"		"%disguisename%"
		"textAlignment"	"center"
		"auto_wide_tocontents" "1"
		"pin_to_sibling" "DisguiseNameLabel"
	}
	"WeaponNameLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"WeaponNameLabel"
		"font"			"m0refont9"
		"xpos"			"cs-0.5"
		"ypos"			"c132"
		"ypos_minmode"			"c154"
		"zpos"			"1"
		"wide"			"190"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor"		"theme"
		"labelText"		"%weaponname%"
		"textAlignment"	"center"
	}
	"WeaponNameLabelshadow"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"WeaponNameLabelshadow"
		"font"			"m0refont9"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"190"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor"		"black"
		"labelText"		"%weaponname%"
		"textAlignment"	"center"
		"pin_to_sibling" "WeaponNameLabel"
	}
	"SpectatorGUIHealth"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"SpectatorGUIHealth"
		"xpos"			"-12"
		"ypos"			"0"
		"wide"			"60"
		"tall"			"32"
		"visible"			"1"
		"enabled"			"1"	
		"HealthBonusPosAdj"	"10"
		"HealthDeathWarning"	"0.49"
		"TFFont"			"HudFontSmall"
		"HealthDeathWarningColor"	"HUDDeathWarning"
		"TextColor"		"HudOffWhite"
		"pin_to_sibling" "DisguiseNameLabel"
        "pin_corner_to_sibling"  "PIN_CENTER_RIGHT"
        "pin_to_sibling_corner"  "PIN_CENTER_LEFT"
			"PlayerStatusHealthBonusImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthBonusImage"
		"xpos"			"9999"
		"ypos"			"9999"
	}
	}	
	
}
