"Resource/UI/MatchMakingDashboard.res"
{
	"MMDashboard"
	{
		"fieldName"				"MMDashboard"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"cs-0.5"
		"ypos"					"-5"
		"zpos"					"10001"
		"wide"					"f0"
		"tall"					"35"
		"keyboardinputenabled"	"0"

		"collapsed_height"	"0"
		"expanded_height"	"35"
		"resize_time"		"0.2"
	}

	"TopBar"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"TopBar"
		"xpos"			"cs-0.5"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"35"
		"visible"		"1"
		"proportionaltoparent"	"1"

		"pinCorner"		"2"
		"autoResize"	"1"

		"Gradient"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"Gradient"
			"xpos"		"0"
			"ypos"		"0"
			"wide"		"p0.5"
			"tall"		"f6"
			"zpos"	"0"
			"visible"		"0"
			"enabled"		"1"
			"rotation"		"2"
			"proportionaltoparent"	"1"
			"scaleimage"	"1"
			"mouseinputenabled"	"0"
			"alpha"		"100"

			"image"		"gradient_pure_black"
		}

		"BGPanel"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"BGPanel"
			"xpos"			"cs-0.5"
			"ypos"			"0"
			"zpos"			"-1"
			"wide"			"p1.1"
			"tall"			"f5"
			"visible"		"0"
			"PaintBackgroundType"	"2"
			"border"		"ReplayDefaultBorder"
			"proportionaltoparent"	"1"
		}

		"OuterShadow"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"OuterShadow"
			"xpos"			"cs-0.5"
			"ypos"			"cs-0.5"
			"zpos"			"-2"
			"wide"			"p1.1"
			"tall"			"p1"
			"visible"		"0"
			"PaintBackgroundType"	"2"
			"border"		"OuterShadowBorder"
			"proportionaltoparent"	"1"
		}
		"ToggleChatButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"ToggleChatButton"
			"xpos"			"0"
			"ypos"			"5"
			"zpos"			"100"
			"wide"			"o1"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"font"			"HudFontSmallestBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"toggle_chat"
			"proportionaltoparent"	"1"
			"labeltext"		""
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"
			"actionsignallevel"	"2"
			"roundedcorners"	"0"

			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"

			"armedBgColor_override"		"0 0 0 150"
			"defaultBgColor_override"	"0 0 0 75"
			"depressedBgColor_override"	"theme"
			"SubImage"
			{
				"wide" "0"
			}
		}
		"chatimage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"chatimage"
			"xpos"			"-3"
			"ypos"			"-3"
			"zpos"			"101"
			"wide"			"15"
			"tall"			"15"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"
			"proportionaltoparent"	"1"
			"image"			"glyph_chat"
			"pin_to_sibling" "ToggleChatButton"
			"mouseinputenabled" "0"
		}
		"chatimageshadow"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"chatimageshadow"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"101"
			"wide"			"15"
			"tall"			"15"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"
			"proportionaltoparent"	"1"
			"image"			"glyph_chat"
			"drawcolor" "black"
			"pin_to_sibling" "chatimage"
			"mouseinputenabled" "0"
		}

		"PartySlot0"
		{
			"ControlName"	"CDashboardPartyMember"
			"fieldName"		"PartySlot0"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"o1"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"proportionaltoparent"	"1"
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"
			"bgcolor_override" "0 0 0 75"
			"party_slot"	"0"
			"pin_to_sibling" "ToggleChatButton"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
		}

		"PartySlot1"
		{
			"ControlName"	"CDashboardPartyMember"
			"fieldName"		"PartySlot1"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"o1"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"proportionaltoparent"	"1"
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"

			"bgcolor_override" "0 0 0 75"

			"party_slot"	"1"
			"pin_to_sibling" "PartySlot0"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
		}

		"PartySlot2"
		{
			"ControlName"	"CDashboardPartyMember"
			"fieldName"		"PartySlot2"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"o1"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"proportionaltoparent"	"1"
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"

			"bgcolor_override" "0 0 0 75"

			"party_slot"	"2"
			"pin_to_sibling" "PartySlot1"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
		}

		"PartySlot3"
		{
			"ControlName"	"CDashboardPartyMember"
			"fieldName"		"PartySlot3"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"o1"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"proportionaltoparent"	"1"
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"

			"bgcolor_override" "0 0 0 75"

			"party_slot"	"3"
			"pin_to_sibling" "PartySlot2"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
		}

		"PartySlot4"
		{
			"ControlName"	"CDashboardPartyMember"
			"fieldName"		"PartySlot4"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"o1"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"proportionaltoparent"	"1"
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"

			"bgcolor_override" "0 0 0 75"

			"party_slot"	"4"
			"pin_to_sibling" "PartySlot3"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
		}

		"PartySlot5"
		{
			"ControlName"	"CDashboardPartyMember"
			"fieldName"		"PartySlot5"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"o1"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"proportionaltoparent"	"1"
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"
			"paintBackgroundType" "2"
			"roundedcorners"	"8"

			"bgcolor_override" "0 0 0 75"

			"party_slot"	"5"
			"pin_to_sibling" "PartySlot4"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
		}
		"Bg"
		{
			"ControlName"								"EditablePanel"
			"fieldName"									"bg"
			"xpos"										"1"
			"ypos"										"1"
			"zpos"										"-10"
			"wide"										"470"
			"tall"										"260"
			"visible"									"1"
			"enabled"									"1"
			"bgcolor_override"									"0 0 0 75"
			"paintBackgroundType" "2"
			"pin_to_sibling" "PartySlot5"
			"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
			"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		}
		"QueueContainer"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"QueueContainer"
			"xpos"			"cs-0.5"
			"ypos"			"-50"
			"zpos"			"111"
			"wide"			"182"
			"tall"			"f0"
			"visible"		"1"
			"proportionaltoparent"	"1"

			"OuterShadow"
			{
				"ControlName"	"Panel"
				"fieldName"		"OuterShadow"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"-1"
				"wide"			"f0"
				"tall"			"f0"
				"visible"		"0"
				"proportionaltoparent"	"1"

				"border"		"OuterShadowBorderThin"
			}

			"BGPanel"
			{
				"ControlName"	"Panel"
				"fieldName"		"BGPanel"
				"xpos"			"cs-0.5"
				"ypos"			"cs-0.5"
				"zpos"			"0"
				"wide"			"f4"
				"tall"			"f4"
				"visible"		"0"
				"proportionaltoparent"	"1"

				"border"		"ReplayDefaultBorder"
			}
			"Bg12"
			{
				"ControlName"								"EditablePanel"
				"fieldName"									"bg12"
				"xpos"										"cs-0.5"
				"ypos"										"5"
				"zpos"										"-10"
				"wide"										"180"
				"tall"										"20"
				"visible"									"1"
				"enabled"									"1"
				"bgcolor_override"									"0 0 0 75"
				"paintBackgroundType" "2"
				"paintBackground" "1"
				"roundedcorners" "12"
				"proportionaltoparent" "1"
			}
			"Bg22"
			{
				"ControlName"								"EditablePanel"
				"fieldName"									"bg22"
				"xpos"										"cs-0.5"
				"ypos"										"5"
				"zpos"										"-10"
				"wide"										"f0"
				"tall"										"21"
				"visible"									"1"
				"enabled"									"1"
				"bgcolor_override"									"0 0 0 75"
				"paintBackgroundType" "2"
				"paintBackground" "1"
				"roundedcorners" "12"
				"proportionaltoparent" "1"
			}
			"QueueLogoButton"
			{
				"ControlName"	"Button"
				"fieldName"		"QueueLogoButton"
				"xpos"			"1"
				"ypos"			"cs-0.5+5"
				"zpos"			"10"
				"wide"			"o1"
				"tall"			"f4"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"labeltext"		""
				"font"			"HudFontSmallBold"
				"textAlignment"	"center"
				"dulltext"		"0"
				"brighttext"	"0"
				"default"		"1"
				"Command"		"queue_logo_clicked"
				"proportionaltoparent"	"1"
				"actionsignallevel"	"3"
				"button_activation_type"	"1"
			
				"paintbackground"	"0"
				"paintborder"		"0"				
			}		

			"CTFLogoPanel"
			{
				"ControlName"	"CTFLogoPanel"
				"fieldname"		"CTFLogoPanel"
				"xpos"			"2"
				"ypos"			"cs-0.5-3"
				"zpos"			"5"
				"wide"			"o1"
				"tall"			"20"
				"visible"		"0"
				"proportionaltoparent"	"1"

				"radius"		"6"
				"velocity"		"75"

				"fgcolor_override"	"white"
				"drawcolor_override"	"white"
			}
			"CTFLogoPanelCustom"
			{
				"ControlName"	"CTFLogoPanel"
				"fieldname"		"CTFLogoPanelCustom"
				"xpos"			"2"
				"ypos"			"cs-0.5-3"
				"zpos"			"5"
				"wide"			"o1"
				"tall"			"20"
				"visible"		"1"
				"proportionaltoparent"	"1"

				"radius"		"6"
				"velocity"		"75"

				"fgcolor_override"	"white"
				"drawcolor_override"	"white"
			}
			"CTFLogoPanelCustomShadow"
			{
				"ControlName"	"CTFLogoPanel"
				"fieldname"		"CTFLogoPanelCustomShadow"
				"xpos"			"-1"
				"ypos"			"-1"
				"zpos"			"5"
				"wide"			"o1"
				"tall"			"20"
				"visible"		"1"
				"proportionaltoparent"	"1"

				"radius"		"6"
				"velocity"		"75"

				"fgcolor_override"	"black"
				"drawcolor_override"	"black"
				"pin_to_sibling" "CTFLogoPanelCustom"
			}
			"QueueText"
			{
				"ControlName"	"CAutoFittingLabel"
				"fieldName"		"QueueText"
				"xpos"			"cs-0.5"
				"ypos"			"cs-0.5-3"
				"wide"			"f55"
				"zpos"			"100"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"font"			"m0refont11shadow"
				"fgcolor_override"	"white"
				"textAlignment"	"center"
				"labelText"		"%queue_state%"
				"proportionaltoparent"	"1"
				"mouseinputenabled"	"0"
			}

			"MultiQueuesManageButton"
			{
				"ControlName"	"CExImageButton"
				"fieldName"		"MultiQueuesManageButton"
				"xpos"			"rs1-7"
				"ypos"			"cs-0.5-3"
				"zpos"			"10"
				"wide"			"12"
				"tall"			"12"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"labeltext"		""
				"font"			"HudFontSmallBold"
				"textAlignment"	"center"
				"dulltext"		"0"
				"brighttext"	"0"
				"default"		"1"
				"sound_depressed"	"UI/buttonclick.wav"
				"sound_released"	"UI/buttonclickrelease.wav"
				"Command"		"manage_queues"
				"proportionaltoparent"	"1"
				"actionsignallevel"	"3"
			
				"paintbackground"	"0"
			
						"armedBgColor_override"		"theme"
		"armedFgColor_override"		"white"
		"depressedBgColor_override"	"theme"
		"depressedFgColor_override"	"white"
		"defaultBgColor_override" "0 0 0 75"
			
				"image_drawcolor"	"255 255 255 255"
				"SubImage"
				{
					"ControlName"	"ImagePanel"
					"fieldName"		"SubImage"
					"xpos"			"cs-0.5"
					"ypos"			"cs-0.5"
					"zpos"			"1"
					"wide"			"f0"
					"tall"			"f0"
					"visible"		"1"
					"enabled"		"1"
					"image"			"glyph_options"
					"scaleImage"	"1"
					"drawcolor"	"255 255 255 255"
					"proportionaltoparent" "1"
				}				
			}		
			"CloseButton"
			{
				"ControlName"	"CExImageButton"
				"fieldName"		"CloseButton"
				"xpos"			"rs1-7"
				"ypos"			"cs-0.5-3"
				"zpos"			"20"
				"wide"			"34"
				"tall"			"11"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"labeltext"		"close"
				"font"			"m0refont11shadow"
				"textAlignment"	"center"
				"dulltext"		"0"
				"brighttext"	"0"
				"default"		"1"
				"sound_depressed"	"UI/buttonclick.wav"
				"sound_released"	"UI/buttonclickrelease.wav"
				"Command"		"leave_queue"
				"proportionaltoparent"	"1"
				"actionsignallevel"	"3"
				"fgcolor_override" "white"
				"mouseinputenabled" "1"
			
				"paintbackground"	"0"
			
				"defaultFgColor_override" "white"
				"armedFgColor_override" "theme"
				"depressedFgColor_override" "theme"		
			}		
		}

		"JoinPartyLobbyContainer"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"JoinPartyLobbyContainer"
			"xpos"			"cs-0.5"
			"ypos"			"-50"
			"zpos"			"110"
			"wide"			"182"
			"tall"			"f0"
			"visible"		"1"
			"proportionaltoparent"	"1"

			"OuterShadow"
			{
				"ControlName"	"Panel"
				"fieldName"		"OuterShadow"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"-1"
				"wide"			"0"
				"tall"			"0"
				"visible"		"1"
				"proportionaltoparent"	"1"

				"border"		"OuterShadowBorderThin"
			}

			"BGPanel"
			{
				"ControlName"	"Panel"
				"fieldName"		"BGPanel"
				"xpos"			"cs-0.5"
				"ypos"			"cs-0.5"
				"zpos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"1"
				"proportionaltoparent"	"1"

				"border"		"ReplayDefaultBorder"
			}
			"Bg12"
			{
				"ControlName"								"EditablePanel"
				"fieldName"									"bg12"
				"xpos"										"cs-0.5"
				"ypos"										"5"
				"zpos"										"-10"
				"wide"										"180"
				"tall"										"20"
				"visible"									"1"
				"enabled"									"1"
				"bgcolor_override"									"0 0 0 75"
				"paintBackgroundType" "2"
				"paintBackground" "1"
				"roundedcorners" "12"
				"proportionaltoparent" "1"
			}
			"Bg22"
			{
				"ControlName"								"EditablePanel"
				"fieldName"									"bg22"
				"xpos"										"cs-0.5"
				"ypos"										"5"
				"zpos"										"-10"
				"wide"										"f0"
				"tall"										"21"
				"visible"									"1"
				"enabled"									"1"
				"bgcolor_override"									"0 0 0 75"
				"paintBackgroundType" "2"
				"paintBackground" "1"
				"roundedcorners" "12"
				"proportionaltoparent" "1"
			}

			"PromptText"
			{
				"ControlName"	"Label"
				"fieldName"		"PromptText"
				"xpos"			"cs-0.5"
				"ypos"			"cs-0.5-3"
				"wide"			"f55"
				"zpos"			"100"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"font"			"m0refont11shadow"
				"fgcolor_override"	"white"
				"textAlignment"	"west"
				"labelText"		"#TF_MM_JoinPartyLobby_Prompt"
				"proportionaltoparent"	"1"
				"mouseinputenabled"	"0"
			}		

			"JoinNowButton"
			{
				"ControlName"	"CExButton"
				"fieldName"		"JoinNowButton"
				"xpos"			"rs1-10"
				"ypos"			"rs1-9-3"
				"wide"			"40"
				"zpos"			"100"
				"tall"			"15"

				if_queued
				{
					"xpos"			"cs-0.5"
					"wide"			"150"
				}
				
				"autoResize"	"0"
				"pinCorner"		"3"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"font"			"HudFontSmallestBold"
				"textAlignment"	"center"
				"dulltext"		"0"
				"brighttext"	"0"
				"Command"		"join_party_match"
				"proportionaltoparent"	"1"
				"labeltext"		"#TF_MM_JoinPartyLobby_Join"
				"mouseinputenabled"	"1"
				"keyboardinputenabled"	"0"
				"actionsignallevel"	"3"

						"armedBgColor_override"		"theme"
		"armedFgColor_override"		"white"
		"depressedBgColor_override"	"theme"
		"depressedFgColor_override"	"white"
		"defaultBgColor_override" "0 0 0 75"

				"sound_depressed"	"UI/buttonclick.wav"
				"sound_released"	"UI/buttonclickrelease.wav"
			}
		}

		"QuitButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"QuitButton"
			"xpos"			"rs1"
			"ypos"			"5"
			"zpos"			"100"
			"wide"			"20"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"font"			"HudFontSmallBold"
			"textAlignment"	"west"
			"textinsetx"	"0"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"quit"
			"proportionaltoparent"	"1"
			"labeltext"		""
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"
			"actionsignallevel"	"2"
			"RoundedCorners"	"0"

			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"

			"armedBgColor_override"		"0 0 0 150"
			"defaultBgColor_override"	"0 0 0 75"

			"defaultFgColor_override" "white"
			"armedFgColor_override" "white"
			"depressedBgColor_override"	"theme"

			"image_drawcolor"	"white"
			"image_armedcolor"	"white"

			"SubImage"
			{
				"wide"			"0"
			}
		}
		"dcquit"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"dcquit"
			"xpos"			"-4"
			"ypos"			"-3"
			"zpos"			"101"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"
			"proportionaltoparent"	"1"
			"image"			"glyph_disconnect"
			"drawcolor_override" "white"
			"pin_to_sibling" "QuitButton"
			"mouseinputenabled" "0"
		}
		"dcquitShadow"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"dcquitShadow"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"101"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"
			"proportionaltoparent"	"1"
			"image"			"glyph_disconnect"
			"drawcolor_override" "black"
			"pin_to_sibling" "dcquit"
			"mouseinputenabled" "0"
		}

		"DisconnectButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"DisconnectButton"
			"xpos"			"rs1"
			"ypos"			"5"
			"zpos"			"100"
			"wide"			"20"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"font"			"HudFontSmallBold"
			"textAlignment"	"west"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"quit"
			"proportionaltoparent"	"1"
			"labeltext"		""
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"
			"actionsignallevel"	"2"
			"RoundedCorners"	"0"

			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"

			"armedBgColor_override"		"0 0 0 150"
			"defaultBgColor_override"	"0 0 0 75"
			"depressedBgColor_override"	"theme"

			"defaultFgColor_override" "white"
			"armedFgColor_override" "white"

			"image_drawcolor"	"white"
			"image_armedcolor"	"white"

			"SubImage"
			{
				"wide"			"0"
			}
		}


		"FindAGameButtonCustom"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"FindAGameButtonCustom"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"20" 
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"font"			"HudFontSmallBold"
			"textAlignment"	"west"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"find_game"
			"proportionaltoparent"	"1"
			"labeltext"		""
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"
			"actionsignallevel"	"2"
			"roundedcorners"	"4"

			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"

			"armedBgColor_override"		"0 0 0 150"
			"defaultBgColor_override"	"0 0 0 75"
			"depressedBgColor_override"	"theme"

			"defaultFgColor_override" "white"
			"armedFgColor_override" "white"
			"image_drawcolor"	"white"
			"image_armedcolor"	"white"
			"pin_to_sibling" "QuitButton"
			"pin_corner_to_sibling" "PIN_TOPRIGHT"
			"pin_to_sibling_corner" "PIN_TOPLEFT"
		}
		"Spin"
		{
			"ControlName"	"CTFLogoPanel"
			"fieldName"		"Spin"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"101"
			"wide"			"20"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"
			"proportionaltoparent"	"1"
			"mouseinputenabled" "0"

			"radius"		"6"
			"velocity"		"20"

			"fgcolor_override"	"white"
			"drawcolor_override"	"white"
			"pin_to_sibling" "FindAGameButtonCustom"
		}
		"SpinShadow"
		{
			"ControlName"	"CTFLogoPanel"
			"fieldName"		"SpinShadow"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"101"
			"wide"			"20"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"
			"proportionaltoparent"	"1"
			"mouseinputenabled" "0"

			"radius"		"6"
			"velocity"		"20"

			"fgcolor_override"	"black"
			"drawcolor_override"	"black"
			"pin_to_sibling" "spin"
		}
		"Bg2"
		{
			"ControlName"								"EditablePanel"
			"fieldName"									"bg2"
			"xpos"										"1"
			"ypos"										"1"
			"zpos"										"-10"
			"wide"										"470"
			"tall"										"260"
			"visible"									"1"
			"enabled"									"1"
			"bgcolor_override"									"0 0 0 75"
			"paintBackgroundType" "2"
			"pin_to_sibling" "FindAGameButtonCustom"
			"pin_corner_to_sibling" "PIN_BOTTOMLEFT"
			"pin_to_sibling_corner" "PIN_BOTTOMLEFT"
		}
		"FindAGameButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"FindAGameButton"
			"xpos"			"999"
			"ypos"			"999"
			"zpos"			"100"
			"wide"			"0" 
			"tall"			"0"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"font"			"HudFontSmallBold"
			"textAlignment"	"west"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"find_game"
			"proportionaltoparent"	"1"
			"labeltext"		""
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"
			"actionsignallevel"	"2"
			"roundedcorners"	"1"

			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"

			"armedBgColor_override"		"0 0 0 150"
			"defaultBgColor_override"	"0 0 0 75"
			"depressedBgColor_override"	"theme"

			"defaultFgColor_override" "white"
			"armedFgColor_override" "white"
			"image_drawcolor"	"white"
			"image_armedcolor"	"white"


			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"cs-0.5"
				"ypos"			"cs-0.5"
				"zpos"			"1"
				"wide"			"f6"
				"tall"			"f6"
				"visible"		"1"
				"enabled"		"1"
				"scaleImage"	"1"
				"proportionaltoparent"	"1"
				"image"			"glyph_multiplayer"
				"drawcolor_override" "white"
			}
		}
		"ResumeButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"ResumeButton"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"0"
			"wide"			"0" [$POSIX]
			"tall"			"0"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"0"
			"enabled"		"0"
			"tabPosition"	"0"
			"font"			"HudFontSmallBold"
			"textAlignment"	"west"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"resume_game"
			"proportionaltoparent"	"1"
			"labeltext"		"#MMenu_ResumeGame"
			"mouseinputenabled"	"1"
			"keyboardinputenabled"	"0"
			"actionsignallevel"	"2"
			"roundedcorners"	"1"
			"textinsety"	"2.5"
			"textinsetx"	"26"
			"use_proportional_insets"	"1"

			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"

		//	"armedBgColor_override"		"CreditsGreen"
		//	"defaultBgColor_override"	"GreenSolid"

			"defaultFgColor_override" "white"
			"armedFgColor_override" "white"
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"235 226 202 255"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"6"
				"ypos"			"10"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"scaleImage"	"1"
				"proportionaltoparent"	"1"
				"image"			"icon_resume"
				"drawcolor_override" "white"
			}
		}
	}
}
