"Resource/UI/TargetID.res"
{
	"TargetNameLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TargetNameLabel"
		"font"			"blank"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"640"
		"tall"			"1"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	
	"TargetDataLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TargetDataLabel"
		"font"			"blank"
		"xpos"			"0"
		"ypos"			"0"	[$WIN32]
		"zpos"			"1"
		"wide"			"640"
		"tall"			"1"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"Left"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"SpectatorGUIHealth"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"SpectatorGUIHealth"
		"xpos"			"cs-0.5"
		"ypos"			"cs-0.5"
		"wide"			"640"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"	
		"HealthBonusPosAdj"	"10"
		"HealthDeathWarning"	"0.49"
		"font" "typosterReg12"
		"TFFont"		"typosterReg12"
		"HealthDeathWarningColor"	"low"
		"TextColor"		"HudOffWhite"
		"proportionaltoparent" "1"

		"PlayerStatusHealthValue"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PlayerStatusHealthValue"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"f0"
			"tall"			"f0"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%Health%"
			"textAlignment"	"center"	
			"font"			"m0refont12"
			"fgcolor"		"white"
			"proportionaltoparent" "1"
		}	
		"PlayerStatusHealthValueShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PlayerStatusHealthValueShadow"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"5"
			"wide"			"f0"
			"tall"			"f0"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%Health%"
			"textAlignment"	"center"	
			"font"			"m0refont12"
			"fgcolor"		"black"
			"pin_to_sibling" "PlayerStatusHealthValue"
			"proportionaltoparent" "1"
		}	
		"PlayerStatusHealthBonusImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatusHealthBonusImage"
			"xpos"			"cs-0.5"
			"ypos"		"cs-0.5"
			"zpos"			"3"
			"wide"			"12"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../hud/health_over_bg"
			"scaleImage"	"1"	
			"proportionaltoparent" "1"
		}
	}	
	"TargetNameLabelCustom"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"TargetNameLabelCustom"
		"font"			"typosterReg9"
		"xpos"			"0"
		"ypos"			"-17"
		"zpos"			"1"
		"wide"			"640"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%targetname%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"fgcolor" "theme"
		"pin_to_sibling" "SpectatorGUIHealth"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_BOTTOMLEFT"
	}
	"TargetNameLabelCustomShadow"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"TargetNameLabelCustomShadow"
		"font"			"typosterReg9"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"641"
		"tall"			"21"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%targetname%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"fgcolor" "0 0 0 255"
		"pin_to_sibling" "TargetNameLabelCustom"
	}
		
	"TargetDataLabelCustom"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"TargetDataLabelCustom"
		"font"			"typosterReg8"
		"xpos"			"0"
		"ypos"			"-12"	[$WIN32]
		"zpos"			"1"
		"wide"			"640"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%targetdata%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"fgcolor" "theme"
		"pin_to_sibling" "TargetNameLabelCustom"
	}
	"TargetDataLabelCustomShadow"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"TargetDataLabelCustomShadow"
		"font"			"typosterReg8"
		"xpos"			"0"
		"ypos"			"0"	[$WIN32]
		"zpos"			"1"
		"wide"			"641"
		"tall"			"21"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%targetdata%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"fgcolor" "0 0 0 255"
		"pin_to_sibling" "TargetDataLabelCustom"
	}
	
	"AmmoIcon"{"ControlName"	"ImagePanel"	"fieldName"		"AmmoIcon" "xpos"			"9999" "ypos"			"9999" "wide"			"0" "tall"			"0" "visible"		"0" "enabled"		"0" "image"			"../hud/leaderboard_class_heavy" "scaleImage"	"1"}
	"KillStreakIcon"{ "ControlName"	"ImagePanel" "fieldName"		"KillStreakIcon" "xpos"			"9999" "ypos"			"9999" "wide"			"0" "tall"			"0" "visible"		"0" "enabled"		"0" "image"			"../hud/leaderboard_streak" "scaleImage"	"1"}
	"MoveableSubPanel"{"ControlName"		"EditablePanel" "fieldName"		"MoveableSubPanel" "xpos"			"99999" "ypos"			"99999" "zpos"			"0" "wide"			"0" "tall"			"0" "visible"		"0" "enabled"		"0"	}
	"AvatarImage"{"ControlName"	"CAvatarImagePanel" "fieldName"		"AvatarImage" "xpos"			"99999" "ypos"			"99999" "zpos"			"0" "wide"			"0" "tall"			"0" "visible"		"0" "enabled"		"0"	}	
}
