"Resource/UI/HudAmmoWeapons.res"
{
	"HudScopeChargeCustom"
	{
		"fieldName" "HudScopeChargeCustom"
		"ControlName" "ImagePanel"
		"visible" "1"
		"enabled" "1"
		"xpos"	 "cs-0.5"
		"ypos"	 "c-16"
		"wide"	 "55"
		"tall"	 "110"//14
		"image" "replay/thumbnails/sniperscope_numbers"
		"scaleImage" "1"
	}
	"anchor"
	{
		"ControlName" "Panel"
		"fieldName" "anchor"
		"xpos"		"c36"
		"ypos"		"r150"
		"wide"		"200"
		"tall"		"80"
		"visible" "1"
		"enabled" "1"
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"DemiBold46"
		"fgcolor"		"Garm3nAmmo"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"			"5"
		"wide"	"100" 
		"tall"	"56" 
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"
		"labelText"		"%Ammo%"
		"pin_to_sibling" "anchor"
		
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"DemiBold46Blur"
		"fgcolor"		"BlurShadow"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"			"4"
		"wide"	"100" 
		"tall"	"56" 
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
		"pin_to_sibling" "AmmoInClip"
	}
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"	"Book32"
		"fgcolor"		"Garm3nAmmoRes"
		"xpos"	"4"
		"ypos"			"-1"
		"zpos"			"5"
		"wide"			"120"
		"tall"			"56"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%AmmoInReserve%"
		"pin_to_sibling" "AmmoInClip"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_TOPRIGHT"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"	"Book32blur"
		"fgcolor"		"BlurShadow"
		"xpos"	"0"
		"ypos"			"0"
		"zpos"			"4"
		"wide"			"120"
		"tall"			"56"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%AmmoInReserve%"
		"pin_to_sibling" "AmmoInReserve"
	}
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"DemiBold46"
		"fgcolor"		"Garm3nAmmo"
		"xpos"	"-44"
		"ypos"	"0"
		"zpos"			"5"
		"wide"	"100" 
		"tall"	"56" 
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"
		"labelText"		"%Ammo%"
		"pin_to_sibling" "anchor"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"DemiBold46Blur"
		"fgcolor"		"BlurShadow"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"			"4"
		"wide"	"100" 
		"tall"	"56" 
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"		
		"labelText"		"%Ammo%"
		"pin_to_sibling" "AmmoNoClip"
	}
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"	
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"3000"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"	
	}
}
