"Resource/UI/HudPlayerHealth.res"
{
	"HudPlayerHealth"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"HudPlayerHealth"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"2"
		"wide"										"f0"
		"tall"										"f0"
		"visible"									"1"
		"enabled"									"1"
		"HealthBonusPosAdj"							"35"
		"HealthDeathWarning"						"0.49"
		"HealthDeathWarningColor"					"255 0 0 255"
	}

	//==================================================================================================================================================
	// HEALTH ANCHOR
	// This element can be used to move all the health elements at the same time
	//==================================================================================================================================================
	"HealthAnchor"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"HealthAnchor"
		"xpos"										"c-140"
		"ypos"										"c103"
		"zpos"										"0"
		"wide"										"2"
		"tall"										"80"
		"visible"									"0"
		"enabled"									"1"
		"alpha"										"0"
	}

	//==================================================================================================================================================
	// BUFF - HURT CROSS
	//==================================================================================================================================================
	"PlayerStatusHealthBonusImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusHealthBonusImage"
		"xpos"										"c-170+13"
		"xpos_minmode"										"9999999"
		"ypos"										"270+90"
		"zpos"										"-4"
		"wide"										"34"
		"tall"										"34"
		"visible"									"0"
		"enabled"									"1"
		"image"										"../hud/health_over_bg"
		//"image"										"replay/thumbnails/over"
		"scaleImage"								"1"
	}

	//==================================================================================================================================================
	// PLAYER HEALTH
	//==================================================================================================================================================
			"cross"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"cross"
		"xpos"										"cs-0.5"//c-172
		"ypos"										"cs-0.5"//c114
		"zpos"										"1"
		"wide"										"156"//45
		"tall"										"156"   //45
		"visible"									"0"
		"enabled"									"1"
		"image"									"replay/thumbnails/horiz"
		"scaleImage"								"1"
		"alpha" "255"
	}
				"1"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"1"
		"xpos"										"cs-0.5"//c-172
		"ypos"										"cs-0.5"//c114
		"zpos"										"1"
		"wide"										"1"//45
		"tall"										"1"   //45
		"visible"									"0"
		"enabled"									"1"
		"fillcolor"									"white"
		"scaleImage"								"1"
	}
					"2"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"2"
		"xpos"										"cs-0.5"//c-172
		"ypos"										"cs-0.5"//c114
		"zpos"										"1"
		"wide"										"2"//45
		"tall"										"2"   //45
		"visible"									"0"
		"enabled"									"1"
		"fillcolor"									"black"
		"scaleImage"								"1"
	}
	"HealthValue"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"HealthValue"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"5"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%Health%"
		"textAlignment"								"center"
		"font"										"m0refont36"
		"fgcolor"									"Health Numbers"

		"pin_to_sibling"							"HealthAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_TOP"
		"pin_to_sibling_corner"						"PIN_CENTER_TOP"
	}

	"HealthValue_Shadow1"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"HealthValue_Shadow1"
		"xpos"										"-1"
		"ypos"										"-1"
		"zpos"										"5"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%Health%"
		"textAlignment"								"center"
		"font"										"m0refont36"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"HealthValue"
	}
			"HealthValue1"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"HealthValue1"
		"xpos"										"-1"
		"ypos"										"-1"
		"zpos"										"5"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%Health%"
		"textAlignment"								"center"
		"font"										"m0refont36"
		"fgcolor"									"black"
		"alpha" "0"

		"pin_to_sibling"							"HealthValue_Shadow1"

	}
			"MaxHealthValue886"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValue886"
		"xpos"										"0"
		"ypos"										"-15"
		"xpos_minmode"										"6"
		"ypos_minmode"										"rs1+15+4"
		"zpos"										"5"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"font_minmode"										"m0refont12"
		"fgcolor"									"health numbers"
		"alpha" "255"

		"pin_to_sibling"							"HealthValue"
		"pin_to_sibling_minmode"							"HudPlayerHealth"
	}
		"MaxHealthValue"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValue"
		"xpos"										"0"
		"ypos"										"-15"
		"xpos_minmode"										"6"
		"ypos_minmode"										"rs1+15+4"
		"zpos"										"5"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"font_minmode"										"m0refont12"
		"fgcolor"									"health buff"
		"alpha" "255"
		"alpha_minmode" "0"

		"pin_to_sibling"							"HealthValue"
		"pin_to_sibling_minmode"							"HudPlayerHealth"
	}
			"MaxHealthValuebg"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValuebg"
		"xpos"										"-1"
		"ypos"										"-1"
		"zpos"										"4"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"1"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"MaxHealthValue"
	}
				"MaxHealthValuebg1"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValuebg1"
		"xpos"										"1"
		"ypos"										"1"
		"zpos"										"4"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"MaxHealthValue"
	}
				"MaxHealthValuebg2"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValuebg2"
		"xpos"										"1"
		"ypos"										"-1"
		"zpos"										"4"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"MaxHealthValue"
	}
				"MaxHealthValuebg3"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValuebg3"
		"xpos"										"-1"
		"ypos"										"1"
		"zpos"										"4"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"MaxHealthValue"
	}
				"MaxHealthValuebg4"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValuebg4"
		"xpos"										"0"
		"ypos"										"-1"
		"zpos"										"4"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"MaxHealthValue"
	}
				"MaxHealthValuebg5"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValuebg5"
		"xpos"										"-1"
		"ypos"										"0"
		"zpos"										"4"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"MaxHealthValue"
	}
				"MaxHealthValuebg6"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValuebg6"
		"xpos"										"1"
		"ypos"										"0"
		"zpos"										"4"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"MaxHealthValue"
	}
				"MaxHealthValuebg7"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"MaxHealthValuebg7"
		"xpos"										"0"
		"ypos"										"1"
		"zpos"										"4"
		"wide"										"150"
		"tall"										"75"
		"visible"									"1"
		"visible_minmode"									"0"
		"enabled"									"1"
		"labelText"									"%MaxHealth%"
		"textAlignment"								"center"
		"font"										"m0refont12"
		"fgcolor"									"black"
		"alpha" "255"

		"pin_to_sibling"							"MaxHealthValue"
	}


	"BG"
	{
		"ControlName"	"ctfImagePanel"
		"fieldName"		"BG"
		"xpos"			"0"
		"ypos"			"rs1+4"
		"zpos"			"4"
		"wide"			"110"
		"tall"			"30"
		"visible"		"0"
		"visible_minmode"		"1"
		"alpha"			"245"
		"image"					"replay/thumbnails/sidegradient"
		"enabled"		"1"
		"scaleImage"	"1"	
	}
		"BG1"
	{
		"ControlName"	"ctfImagePanel"
		"fieldName"		"BG1"
		"xpos"			"0"
		"ypos"			"r26"
		"zpos"			"4"
		"wide"			"110"
		"tall"			"1"
		"visible"		"0"
		"visible_minmode"		"1"
		"alpha"			"185"
		"image"					"replay/thumbnails/sidegradient"
		"enabled"		"1"
		"scaleImage"	"1"	
	}
			"roll"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"roll"
		"xpos"										"c-178"
		"ypos"										"c78"
		"zpos"			"10"
		"wide"			"30"
		"tall"			"30"
		"xpos_minmode"			"86"
		"ypos_minmode"			"r44"
		"wide_minmode"			"36"
		"tall_minmode"			"36"
		"visible"		"0"
		"alpha"			"255"
		"image"					"replay/thumbnails/roll"
		"enabled"		"1"
		"scaleImage"	"1"	
		"drawcolor" "white"
		"drawcolor_minmode" "Health Buff"
	}
				"Me"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"me"
		"xpos"										"c-176"
		"ypos"										"c78"
		"zpos"			"10"
		"wide"			"30"
		"tall"			"0"
		"xpos_minmode"			"89"
		"ypos_minmode"			"r39"
		"wide_minmode"			"28"
		"tall_minmode"			"28"
		"visible"		"1"
		"alpha"			"255"
		"image"					"replay/thumbnails/me"
		"enabled"		"1"
		"scaleImage"	"1"	
	}
					"Mes"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"mes"
		"xpos"										"c-178"
		"ypos"										"c78"
		"zpos"			"10"
		"wide"			"30"
		"tall"			"0"
		"xpos_minmode"			"-1"
		"ypos_minmode"			"-1"
		"wide_minmode"			"28"
		"tall_minmode"			"28"
		"visible"		"1"
		"alpha"			"255"
		"image"					"replay/thumbnails/me"
		"enabled"		"1"
		"scaleImage"	"1"	
		"drawcolor"    "black"
		"pin_to_sibling"    "me"
	}
		"hp"
	{
		"ControlName"	"ctfImagePanel"
		"fieldName"		"hp"
		"xpos"			"6"
		"ypos"			"r18"
		"zpos"			"5"
		"wide"			"11"
		"tall"			"11"
		"visible"		"0"
		"visible_minmode"		"1"
		"alpha"			"255"
		"image"					"replay/thumbnails/hp"
		"enabled"		"1"
		"scaleImage"	"1"	
		"drawcolor" "Health Numbers"
	}
			"hplow"
	{
		"ControlName"	"ctfImagePanel"
		"fieldName"		"hplow"
		"xpos"			"6"
		"ypos"			"r18-1"
		"zpos"			"6"
		"wide"			"11"
		"tall"			"11"
		"visible"		"0"
		"visible_minmode"		"1"
		"alpha"			"0"
		"image"					"replay/thumbnails/hp"
		"enabled"		"1"
		"scaleImage"	"1"	
		"drawcolor" "health hurt"
	}
			"hpbg"
	{
		"ControlName"	"ctfImagePanel"
		"fieldName"		"hpbg"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"5"
		"wide"			"11"
		"tall"			"11"
		"visible"		"0"
		"visible_minmode"		"1"
		"alpha"			"255"
		"image"					"replay/thumbnails/hp"
		"enabled"		"1"
		"scaleImage"	"1"	
		"drawcolor" "black"
		"pin_to_sibling"    "hp"
	}
	"healthbar"
	{	
		"ControlName"	"ContinuousProgressBar"	"fieldName"	"healthbar"
		"xpos"	"64"	"ypos"	"rs2.4+1"	"zpos"	"10"	"wide"	"34"	"tall"	"7"	"textAlignment"	"Left"
		"visible"	"0"	 "visible_minmode"	"1" "enabled"	"1"
		"variable"	"Health"
		"FGcolor_override"		"health numbers" "BGcolor_override"		"0 0 0 0"	"alpha"	"255"
	}
		"healthbarlow"
	{	
		"ControlName"	"ContinuousProgressBar"	"fieldName"	"healthbarlow"
		"xpos"	"64"	"ypos"	"rs2.4+1"	"zpos"	"11"	"wide"	"34"	"tall"	"7"	"textAlignment"	"Left"
		"visible"	"0"	 "visible_minmode"	"1" "enabled"	"1"
		"variable"	"Health"
		"FGcolor_override"		"health hurt" "BGcolor_override"		"0 0 0 0"	"alpha"	"0"
	}
		"healthbarS"
	{	
		"ControlName"	"ContinuousProgressBar"	"fieldName"	"healthbarS"
		"xpos"	"-1"	"ypos"	"-1"	"zpos"	"10"	"wide"	"34"	"tall"	"7"	"textAlignment"	"Left"
		"visible"	"0"	 "visible_minmode"	"1" "enabled"	"1"
		"variable"	"Health"
		"FGcolor_override"		"black" "BGcolor_override"		"0 0 0 255"	"alpha"	"255"    "pin_to_sibling"    "healthbar"
	}
			"healthbarS1"
	{	
		"ControlName"	"ContinuousProgressBar"	"fieldName"	"healthbarS1"
		"xpos"	"0"	"ypos"	"0"	"zpos"	"10"	"wide"	"34"	"tall"	"7"	"textAlignment"	"Left"
		"visible"	"0"	 "visible_minmode"	"1" "enabled"	"1"
		"variable"	"Health"
		"FGcolor_override"		"black" "BGcolor_override"		"0 0 0 255"	"alpha"	"255"    "pin_to_sibling"    "healthbar"
	}
	"HealthValueFK"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"HealthValueFK"
		"xpos"										"-35"
		"ypos"										"rs1+29"
		"zpos"										"6"
		"wide"										"150"
		"tall"										"75"
		"visible"									"0"
		"visible_minmode"									"1"
		"enabled"									"1"
		"labelText"									"%Health%"
		"textAlignment"								"center"
		"font"										"m0refont30"
		"fgcolor"									"health numbers"
	}
		"HealthValueFKS"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"HealthValueFKS"
		"xpos"										"-1"
		"ypos"										"-1"
		"zpos"										"5"
		"wide"										"150"
		"tall"										"75"
		"visible"									"0"
		"visible_minmode"									"1"
		"enabled"									"1"
		"labelText"									"%Health%"
		"textAlignment"								"center"
		"font"										"m0refont30"
		"fgcolor"									"black"
		"pin_to_sibling"   "HealthValueFK"
	}
		"HealthValueFKBlur"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"HealthValueFKBlur"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"5"
		"wide"										"150"
		"tall"										"75"
		"visible"									"0"
		"visible_minmode"									"1"
		"enabled"									"1"
		"labelText"									"%Health%"
		"textAlignment"								"center"
		"font"										"m0refont30blur"
		"alpha" "75"
		"fgcolor"									"0 0 0 0"
		"pin_to_sibling"   "HealthValueFK"
	}
			"HealthValueFKBlur2"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"HealthValueFKBlur2"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"6"
		"wide"										"150"
		"tall"										"75"
		"visible"									"0"
		"visible_minmode"									"1"
		"enabled"									"1"
		"labelText"									"%Health%"
		"textAlignment"								"center"
		"font"										"m0refont30blur"
		"alpha" "75"
		"fgcolor"									"0 0 0 0"
		"pin_to_sibling"   "HealthValueFK"
	}

	//==================================================================================================================================================
	// STATUS ICONS ANCHOR
	// Moves all the status icons at the same time
	//==================================================================================================================================================
	"PlayerStatusAnchor"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"PlayerStatusAnchor"
		"xpos"										"-20"
		"ypos"										"0"
		"xpos_minmode"										"110"
		"ypos_minmode"										"70"
		"wide"										"0"
		"tall"										"80"
		"visible"									"1"
		"enabled"									"1"

		"pin_to_sibling"							"HealthValue"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}

	//==================================================================================================================================================
	// STATUS ICONS
	//==================================================================================================================================================
	"PlayerStatusBleedImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusBleedImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"bleed_drop"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatusHookBleedImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusHookBleedImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"bleed_drop_grapple"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatusGasImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusGasImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"covered_in_gas"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatusMilkImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusMilkImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"bleed_drop"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatusMarkedForDeathImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusMarkedForDeathImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"marked_for_death"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatusMarkedForDeathSilentImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusMarkedForDeathSilentImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"marked_for_death"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_MedicUberBulletResistImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_MedicUberBulletResistImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_bullet_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_MedicUberBlastResistImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_MedicUberBlastResistImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_explosion_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_MedicUberFireResistImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_MedicUberFireResistImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_fire_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_MedicSmallBulletResistImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_MedicSmallBulletResistImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_bullet_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_MedicSmallBlastResistImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_MedicSmallBlastResistImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_explosion_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_MedicSmallFireResistImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_MedicSmallFireResistImage"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_fire_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_WheelOfDoom"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_WheelOfDoom"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../signs/death_wheel_whammy"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_SoldierOffenseBuff"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_SoldierOffenseBuff"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_bullet_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_SoldierDefenseBuff"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_SoldierDefenseBuff"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_bullet_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_SoldierHealOnHitBuff"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_SoldierHealOnHitBuff"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../HUD/defense_buff_bullet_blue"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_Parachute"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_Parachute"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"0"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										""
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneStrength"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneStrength"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_strength_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneHaste"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneHaste"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_haste_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneRegen"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneRegen"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_regen_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneResist"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneResist"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_resist_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneVampire"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneVampire"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_vampire_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneReflect"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneReflect"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_reflect_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RunePrecision"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RunePrecision"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_precision_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneAgility"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneAgility"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_agility_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneKnockout"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneKnockout"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_knockout_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneKing"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneKing"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_king_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RunePlague"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RunePlague"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_plague_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatus_RuneSupernova"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatus_RuneSupernova"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"../Effects/powerup_supernova_hud"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"PlayerStatusSlowed"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusSlowed"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"7"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"scaleImage"								"1"
		"image"										"slowed"
		"fgcolor"									"TanDark"
		"pin_to_sibling"							"PlayerStatusAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_RIGHT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}



	//==================================================================================================================================================
	// REMOVED ELEMENTS
	//==================================================================================================================================================

	"PlayerStatusHealthImage"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusHealthImage"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}
	"PlayerStatusHealthImageBG"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"PlayerStatusHealthImageBG"
		"xpos"										"9999"
		"ypos"										"9999"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}
	"PlayerStatusMaxHealthValue"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"PlayerStatusMaxHealthValue"
		"xpos"										"9999"
		"ypos"										"9999"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}
}