"resource/ui/disguisestatuspanel.res"
{
	"itemmodelpanel"
	{
		"ControlName"								"CEmbeddedItemModelPanel"
		"fieldName"									"itemmodelpanel"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"100"
		"tall"										"100"
		"visible"									"1"
		"enabled"									"1"

		"useparentbg"								"1"
		"fov"										"54"
		"start_framed"								"1"
		"disable_manipulation"						"1"

		"model"
		{
			"angles_x"								"10"
			"angles_y"								"130"
			"angles_z"								"0"
		}
	}
	"DisguiseStatusBG"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"DisguiseStatusBG"
		"xpos"										"cs-0.5"
		"ypos"										"r86"
		"zpos"										"-1"
		"wide"										"140"
		"tall"								"26"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"fillcolor"									"m0reblack"
		"alpha" "185"
	}
	"DisguiseNameLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"DisguiseNameLabel"
		"xpos"										"-30"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"110"
		"tall"										"26"
		"visible"									"1"
		"enabled"									"1"
		"labelText"							"%disguisename%"
		"font"										"scaleformname"
		"textAlignment"								"West"
		"fgcolor"									"scaleformcolor"

		"pin_to_sibling"							"DisguiseStatusBG"
	}
	"WeaponNameLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"WeaponNameLabel"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"140"
		"tall"										"11"
		"visible"									"1"
		"enabled"									"1"
		"labelText"							"%weaponname%"
		"font"										"scaleform thin"
		"textAlignment"								"east"
		"fgcolor"							"scaleformcolor"
		"alpha" "200"
		"bgcolor_override" "17 17 17 150"
		"textinsetx" "6"

		"pin_to_sibling"							"DisguiseStatusBG"
		"pin_corner_to_sibling" "PIN_TOPRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
	}
	"SpectatorGUIHealth"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"SpectatorGUIHealth"
		"xpos"										"9999"
		"ypos"										"3"
		"wide"										"45"
		"tall"										"44"
		"visible"									"1"
		"enabled"									"1"
		"HealthBonusPosAdj"							"10"
		"HealthDeathWarning"						"0.49"
		"TFFont"									"HudFontSmall"
		"HealthDeathWarningColor"					"HUDDeathWarning"
		"TextColor"									"HudOffWhite"

		"pin_to_sibling"							"DisguiseStatusBG"
		"pin_corner_to_sibling"						"PIN_CENTER_LEFT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
}