"Resource/HudLayout.res"
{
	"Watermark"
	{
		"ControlName"		"EditablePanel"

		"xpos"				"rs1-2"
		"ypos"				"2"
		"wide"				"76"
		"tall"				"14"
		"proportionaltoparent"	"1"
		"alpha" "255"
		"zpos" "999"

		"bgcolor_override"	"0 0 0 0"
		
		"Bg"
		{
			"ControlName"								"EditablePanel"
			"fieldName"									"bg"
			"xpos"										"cs-0.5"
			"ypos"										"cs-0.5"
			"zpos"										"-11"
			"wide"										"74"
			"tall"										"12"
			"visible"									"1"
			"enabled"									"1"
			"bgcolor_override"									"25 25 25 255"
			"paintBackgroundType" "2"
			"proportionaltoparent" "1"
		}
				"Bggrad"
		{
			"ControlName"								"EditablePanel"
			"fieldName"									"Bggrad"
			"xpos"										"1"
			"ypos"										"cs-0.5"
			"zpos"										"-10"
			"wide"										"70"
			"tall"										"12"
			"visible"									"1"
			"enabled"									"1"
			"bgcolor_override"									"theme"
			"paintBackgroundType" "3"
			"proportionaltoparent" "1"
			"alpha" "25"
		}
		"Bg2"
		{
			"ControlName"								"EditablePanel"
			"fieldName"									"bg2"
			"xpos"										"cs-0.5"
			"ypos"										"cs-0.5"
			"zpos"										"-12"
			"wide"										"f0"
			"tall"										"f0"
			"visible"									"1"
			"enabled"									"1"
			"bgcolor_override"									"75 75 75 255"
			"paintBackgroundType" "2"
			"proportionaltoparent" "1"
			"alpha" "100"
		}
		"frames"
		{
			"ControlName"	"ScalableImagePanel"
			"xpos"			"rs1-14"
			"ypos" "cs-0.5"
			"wide"			"18"
			"tall"			"9"
			"image"			"replay/thumbnails/fps/fps"
			"proportionaltoparent"	"1"

			"drawcolor"		"255 255 255 255"
			"alpha"			"255"
		}
		"fps"
		{
			"ControlName"								"CExLabel"
			"fieldName"									"fps"
			"xpos"										"cs-0.5-4"
			"ypos"										"cs-0.5"
			"zpos"										"2"
			"wide"										"f0"
			"tall"										"f0"
			"visible"									"1"
			"enabled"									"1"
			"labelText"									"fps"
			"textAlignment"								"east"
			"font"										"watermark2"
			"fgcolor"   								"theme"
			"proportionaltoparent" "1"
		}
		"dev"
		{
			"ControlName"								"CExLabel"
			"fieldName"									"dev"
			"xpos"										"cs-0.5-5"
			"ypos"										"cs-0.5"
			"zpos"										"2"
			"wide"										"f0"
			"tall"										"f0"
			"visible"									"1"
			"enabled"									"1"
			"labelText"									"dev"
			"textAlignment"								"center"
			"font"										"watermark2"
			"fgcolor"   									"theme"
			"proportionaltoparent" "1"
		}
		"divider"
		{
			"ControlName"								"CExLabel"
			"fieldName"									"divider"
			"xpos"										"cs-0.5+5"
			"ypos"										"cs-0.5-1"
			"zpos"										"2"
			"wide"										"f0"
			"tall"										"f0"
			"visible"									"1"
			"enabled"									"1"
			"labelText"									"|"
			"textAlignment"								"center"
			"font"										"watermark"
			"fgcolor"   									"theme"
			"proportionaltoparent" "1"
			"alpha" "255"
		}
		"divider2"
		{
			"ControlName"								"CExLabel"
			"fieldName"									"divider2"
			"xpos"										"cs-0.5-14"
			"ypos"										"cs-0.5-1"
			"zpos"										"2"
			"wide"										"f0"
			"tall"										"f0"
			"visible"									"1"
			"enabled"									"1"
			"labelText"									"|"
			"textAlignment"								"center"
			"font"										"watermark"
			"fgcolor"   									"theme"
			"proportionaltoparent" "1"
			"alpha" "255"
		}
		"hello"
		{
			"ControlName"								"CExLabel"
			"fieldName"									"dev"
			"xpos"										"cs-0.5+4"
			"ypos"										"cs-0.5"
			"zpos"										"2"
			"wide"										"f0"
			"tall"										"f0"
			"visible"									"1"
			"enabled"									"1"
			"labelText"									"hello"
			"textAlignment"								"west"
			"font"										"watermark2"
			"fgcolor"   								"white"
			"proportionaltoparent" "1"
		}
	}
}