"resource/ui/targetid.res"
{
    "TargetBGshade"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"TargetBGshade"
		"xpos"										"0"
		"ypos"										"11"
		"zpos"										"-1"
		"wide"										"252"
		"tall"										"12"
		"visible"									"1"
		"enabled"									"1"
		"fillcolor"									"0 0 0 100"
	}
	"TargetNameLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"TargetNameLabel"
		"xpos"										"0"
		"ypos"										"11"
		"zpos"										"1"
		"wide"										"640"
		"tall"										"12"
		"visible"									"1"
		"enabled"									"0"
		"font"										"cata14"
		"labelText"									"%targetname%"
		"textAlignment"								"west"
		"disabledfgcolor2_override"					"White"
	}
		"TargetDataLabel"
	{
		"ControlName"		       					"CExLabel"
		"fieldName"		        					"TargetDataLabel"
		"xpos"			           					"0"
		"ypos"			           					"0"
		"zpos"			           					"1"
		"wide"			           					"280"
		"tall"			           					"9"
		"visible"		          					"1"
		"enabled"		           					"1"
		"font"			           					"cata12Shadow"
		"labelText"		        					"%targetdata%"
		"textAlignment"		     					"north-west"
		"fgcolor"     								"White"
	}
}