"Resource/UI/HudAmmoWeapons.res"
{
	"HudScopeChargeCustom"
	{
		"fieldName" "HudScopeChargeCustom"
		"ControlName" "ImagePanel"
		"visible" "1"
		"enabled" "1"
		"xpos"	 "cs-0.5"
		"ypos"	 "c-16"
		"wide"	 "55"
		"tall"	 "110"//14
		"image" "replay/thumbnails/sniperscope_numbers"
		"scaleImage" "1"
	}
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ammo_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"			
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"4"
		"ypos"			"09999"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ammo_red_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"			
	}
	"anchorammo"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"anchorammo"
		"xpos"			"c146-60"
		"ypos"			"c35+37"
		"xpos_minmode"			"c146+10"
		"ypos_minmode"			"c35+54"
		"zpos"			"5"
		"wide"			"28"
		"tall"			"1"	
		"visible"		"1"
		"enabled"		"1"	
	}
	"AmmoAnchorer"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoAnchorer"
		"font"			"mainfont"
		"fgcolor"		"White"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"5"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"	
		"auto_wide_tocontents" "1"
		"alpha" "0"
		"pin_to_sibling" "anchorammo"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
	} 
	"Ammo"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"Ammo"
		"font"			"mainfont"
		"fgcolor"		"white"
		"xpos"			"36"
		"ypos"			"0"
		"zpos"			"5"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"	
		"alpha" "255"
		"pin_to_sibling" "anchorammo"
	} 
	"AmmoShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoShadow"
		"font"			"mainfont"
		"fgcolor"		"black"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"5"
		"wide"			"101"
		"tall"			"51"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"	
		"alpha" "255"
		"pin_to_sibling" "ammo"
	} 
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"m0refont11"
		"fgcolor"		"reservecolor"
		"xpos"			"2"
		"ypos"			"6"
		"zpos"			"4"
		"wide"			"50"
		"tall"			"25"
		"tall_lodef"	"30"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"/"
		"pin_to_sibling" "ammoanchorer"
		"pin_corner_to_sibling" "7"
        "pin_to_sibling_corner" "5"
		"alpha" "255"
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"m0refont11"
		"fgcolor"		"black"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"4"
		"wide"			"50"
		"tall"			"25"
		"tall_lodef"	"30"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"/"	
		"pin_to_sibling" "AmmoInClip"
		"alpha" "255"
		
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"m0refont11"
		"fgcolor"		"reservecolor"
		"xpos"			"-43"
		"ypos"			"2"
		"zpos"			"4"
		"wide"			"50"
		"tall"			"25"
		"tall_lodef"	"30"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%ammoinreserve%"
		"pin_to_sibling" "AmmoInClip"
		"pin_corner_to_sibling" "7"
        "pin_to_sibling_corner" "5"
		"alpha" "255"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"m0refont11"
		"fgcolor"		"black"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"4"
		"wide"			"50"
		"tall"			"25"
		"tall_lodef"	"30"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%ammoinreserve%"
		"pin_to_sibling" "AmmoInReserve"
		"alpha" "255"
	}									
	"AmmoNoClip"
	{
		"fieldName"		"AmmoNoClip"
		"xpos"			"99999"
		"ypos"			"99999"
		"zpos"			"-9999"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
	}	
	"AmmoNoClipShadow"
	{
		"fieldName"		"AmmoNoClipShadow"
		"xpos"			"99999"
		"ypos"			"99999"
		"zpos"			"-9999"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
		
	}									
}
